language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
    - "pip install -r requirements.txt"

services:
    - couchdb

before_script:
    - curl -X PUT localhost:5984/stristo

# command to run tests
script:
    - python stristo_test.py
